export const UiText = {
    NEXT_LABEL: "▶ NEXT",
    WEAKNESS_FIRE: "炎",
    WEAKNESS_ICE: "氷",
    WEAKNESS_HOLY: "聖",
    WEAKNESS_SLASH: "斬",
    WEAKNESS_PREFIX: "弱点:",
    WEAKNESS_NONE: "弱点:なし",
    TURN_SELECT_TEMPLATE: "▼ {name} の行動選択",
    COMMAND_ATTACK: "攻撃",
    COMMAND_MAGIC: "魔法",
    COMMAND_SKILL: "スキル",
    COMMAND_ITEM: "どうぐ",
    COMMAND_BACK: "戻る",
    TARGET_SELECT: "対象を選択してください",
    SELECT_MAGIC: "魔法を選択",
    SELECT_SKILL: "スキルを選択",
    ITEM_SELECT: "アイテムを選択",
    ITEM_COUNT_TEMPLATE: "{name} ({count})",
    SKILL_COST_TEMPLATE: "{name} ({cost})",
    RAISE_FALLBACK: "命の代償",
    ALL_OUT_TITLE: "トリニティアタックのチャンス！",
    ALL_OUT_CONFIRM: "トリニティアタック",
    ALL_OUT_CANCEL: "しない",
    RELIC_FALLBACK_ICON: "💎",
    RELIC_TITLE_TEMPLATE: "{name}\n{desc}",
    LOG_FULL: "FULL",
    LOG_DOWN: "DOWN",
    LOG_MP: "MP",
    LOG_HP: "HP",
    LOG_ATTACK_TEMPLATE: "{name}の攻撃！",
    LOG_SKILL_TEMPLATE: "{name}の {skill} ",
    LOG_DAMAGE_TEMPLATE: "> {name}に {damage} のダメージ！",
    LOG_HEAL_TEMPLATE: "> {name}の{type}が {amount} 回復した",
    LOG_FULL_HEAL_TEMPLATE: "> {name}のHP・MPが全回復した！",
    LOG_RESURRECT_FULL_TEMPLATE: "{name}が完全な状態で蘇生した！",
    LOG_RESURRECT_TEMPLATE: "> {name}が蘇った！",
    LOG_COVER_READY_TEMPLATE: "{name}は身構えた！",
    LOG_COVER_DESC: " > 仲間への攻撃を身代わりする！",
    LOG_COVER_ACTION_TEMPLATE: " > {protector}が{target}をかばった！",
    LOG_DRAGON_ROAR: "竜の咆哮",
    LOG_DRAGON_ATTACK_UP: " > ドラゴンの攻撃力が激増した！",
    LOG_ALLY_ATTACK_UP: " > 味方の攻撃力が上がった！",
    LOG_REGEN_TEMPLATE: "{name}は天に祈りを捧げた！",
    LOG_REGEN_EFFECT: " > 味方全員に祝福が宿る！",
    LOG_SPLIT_TRIGGER_TEMPLATE: "{name}の体が震えだした...！",
    LOG_SPLIT_TRANSFORM_TEMPLATE: "{name}は3匹に分裂した！",
    LOG_SHADOW_FUSION_START: "影たちが一点に凝縮していく...！",
    LOG_SHADOW_FUSION_END: "「影の支配者」が現れた！！！",
    LOG_DRAGON_TRANSFORM: "『我ガ眠リヲ妨ゲル者ハ...消エ去レ...！！』",
    LOG_BLIZZARD: "猛吹雪が吹き荒れる！",
    LOG_DESPAIR_ATTACK: "覚醒アイスドラゴン『無ニ帰ス...絶対零度！！』",
    LOG_PARTY_WIPE: "パーティは全滅した...",
    LOG_HOPE: "もうだめかと思ったその時...",
    LOG_ZABOCHI_LINE: "？？？『にゃにを諦めているにゃ！？』",
    LOG_ZABOCHI_MIRACLE: "伝説の神猫『ざぼち』が降臨し、奇跡を起こした！",
    LOG_FULL_RECOVERY: "味方全員のHP・MPが全回復！",
    LOG_ZABOCHI_JOIN: "ざぼちが共闘してくれる！",
    LOG_ITEM_USE_TEMPLATE: "{name}は {item} を使った！",
    LOG_CRITICAL: "クリティカルヒット！",
    LOG_STATUS_HP_TEMPLATE: "HP: {current} / {max}",
};
